import { useState } from "react";
import Head from "next/head";
import { fibonacci, sumValues } from "@shared/core";

export default function Home() {
  const [value, setValue] = useState(5);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          value={value.toString()}
          onInput={(e) =>
            setValue(Math.min(e.currentTarget.valueAsNumber || 0, 15))
          }
          type="number"
          min={0}
          max={10}
        />
        <ul>
          <li>
            Fibonnaci of {value} is {fibonacci(value).toFixed(0)}
          </li>
          <li>sumof of [15, 65, 25,98] is {sumValues([15, 65, 25, 98])}</li>
        </ul>
      </main>
    </>
  );
}
